[Jira]
url = "https://issues.apache.org/jira/rest/api/2/search"
jql = '''
project = "HIVE"
AND issuetype = "Bug"
AND status = "Resolved"
AND resolution = "Fixed"
AND fixVersion >= "2.0.0"
'''
fields = "id,key,fixVersions,versions,summary"
maxResults = 1000

[GitHub]
api_url = "https://api.github.com/search/commits"
owner = "apache"           # Nom de l'organisation
repo = "hive"              # Nom du dépôt

